# Generated by Django 5.1.1 on 2024-09-16 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240726_1643'),
        ('users', '0002_user_is_verified_email_emailverification'),
    ]

    operations = [
    ]
